### ISSUE TITLE
查 up 空间的 gRPC Proto 可能有问题？

### ISSUE THREAD

**Issue by djkcyl** [SocialSisterYi/bilibili-API-collect#799]
具体实现在这儿：https://github.com/SK-415/bilireq/blob/main/bilireq/grpc/utils/metadata.py

无论怎么发，这个 `DynSpaceReq` 都会报 `-352` 错误。

```python
await grpc_get_user_dynamics(uid=491589125, auth=auth)
```

```
Traceback (most recent call last):
  File "/root/bilireq/bilireq/grpc/utils/__init__.py", line 48, in wrapper
    result = await func(
  File "/root/bilireq/bilireq/grpc/dynamic/__init__.py", line 26, in grpc_get_user_dynamics
    return await stub.DynSpace(req, **kwargs)
  File "/root/bilireq/.venv/lib/python3.10/site-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "-352"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"-352", grpc_status:2, created_time:"2023-08-28T09:28:45.915381792+08:00"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bilireq/test/test_grpc.py", line 91, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/bilireq/test/test_grpc.py", line 74, in main
    dynamics = await grpc_get_user_dynamics(uid=491589125, auth=auth)
  File "/root/bilireq/bilireq/grpc/utils/__init__.py", line 66, in wrapper
    raise GrpcError(
bilireq.exceptions.GrpcError: 错误码: -352, 信息: -352
```

**Comment by cxw620** [comment]
device 改 android, 版本号改 7380300, channel 改 master 看看
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/70561268/6d6f7813-94b9-4ac3-97f8-2986af384326)

**Comment by Werewolf-Wu** [comment]
我之前爬关注列表每次报错-352后，进去都要求做一个验证码，做了之后就不报错了

**Comment by djkcyl** [comment]
安卓客户端吗？

**Comment by djkcyl** [comment]
> device 改 android, 版本号改 7380300, channel 改 master 看看 ![image](https://user-images.githubusercontent.com/70561268/263595177-6d6f7813-94b9-4ac3-97f8-2986af384326.png)

修改后无效，仍然 -352
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/59153990/ff0ccfd1-9ba9-4352-8f58-4f786572f707)

**Comment by cxw620** [comment]
UA 改了没, 你抓个包看看和正常 APP 请求的差别. 
还有发送时 gzip 要关掉.

**Comment by djkcyl** [comment]
> UA 改了没, 你抓个包看看和正常 APP 请求的差别. 还有发送时 gzip 要关掉.

用的是grpc的请求库，其他所有接口都没问题，只有这一个接口是报错的

**Comment by cxw620** [comment]
最近风控是紧一点.

应该是可以自定义 UA, 关闭 gzip 的.

**Comment by djkcyl** [comment]
貌似没找到关闭 gzip 的方法，好像这个 python 的 grpc 库没提供
ua 的话用的是手机抓包抓来的，修改了 build 也依然不行

**Comment by djkcyl** [comment]
![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/59153990/672b4a35-7fe0-4283-ad7f-e86a5b672fb2)

**Comment by cxw620** [comment]
找到个 example
```py
response, call = client.t_client.with_call(
        pb2.t_client_requests(data=str_random),
        compression=grpc.Compression.Gzip, // 这儿改 grpc.Compression.Deflate 看看
        metadata=((('client_key',"clinet_value"),)),
        timeout=10,
        # wait_for_ready=True,
    )  # timeout超出时长抛出异常
```

> ![image](https://user-images.githubusercontent.com/59153990/263608646-672b4a35-7fe0-4283-ad7f-e86a5b672fb2.png)

eid 那里怎么有个 \u003d, no padding 的.
UA 里面也有版本号, 相对应改一下.
access_key 截取前32位.
grpc.biliapi.net 改 app.bilibili.com.

看看可不可行.

**Comment by djkcyl** [comment]
上面的 json 是手机小黄鸟抓包抓来的， no padding 不清楚是为啥
ua的话版本号对上了，
```
 'user-agent': 'Dalvik/2.1.0 (Linux; U; Android 13; KB2003 '
               'Build/RKQ1.211119.001) 7.38.0 os/android model/KB2003 '
               'mobi_app/android build/7380300 channel/master innerVer/7380300 '
               'osVer/13 network/2 grpc-java-cronet/1.36.1',
```
截取了前 32 位也改了host，仍然报错

**Comment by cxw620** [comment]
发送端 Gzip 关了没

抓个包比对一下正常请求, 或者说 APP 的请求和你 python 程序发出的请求的差异, 包括请求头和发送的二进制内容. 
可以抓包, APP 随意打开个动态, 然后拿 proto 解析一下 APP 请求的内容, 然后复制过来, 确保请求的 DynSpaceReq 是一致的, 然后比对发送的二进制内容.

**Comment by cxw620** [comment]
> 无法复现, 甚至请求头鉴权部分只剩空的`x-bili-device-bin`都可以 你可以试试手写grpc协议, 或者试试换个ip python:

我瞅着就像 gzip 暴露了客户端, 要不然就是 IP 黑了或者 access_key 黑了

**Comment by stmtc233** [comment]
前几天我爬太猛了估计 b站就加了这个-352 换个ip就好了

**Comment by djkcyl** [comment]
> > 无法复现, 甚至请求头鉴权部分只剩空的`x-bili-device-bin`都可以 你可以试试手写grpc协议, 或者试试换个ip python:
> 
> 我瞅着就像 gzip 暴露了客户端, 要不然就是 IP 黑了或者 access_key 黑了...
> 
> 不过手搓 gRPC 消息就真的猛了 😂

那更不对了啊，因为加不加 access_key，甚至换ip，加代理都没用，该不会真是这个python库的问题吧（

**Comment by stmtc233** [comment]
> > > 无法复现，甚至请求头鉴权部分空间的`x-bili-device-bin`都可以你可以尝试手写grpc协议，或者尝试换个ip python：
> > 
> > 
> > 我瞧着就像gzip暴露了客户端，要不然就是IP黑了或者access_key黑了...
> > 手搓gRPC消息就真的猛了😂
> 
> 那更不用了啊，因为加不加access_key，甚至换ip，加代理都没用，该不会真是这个python库的问题吧（

-352应该是23号加的 我感觉就是ip问题 23号之前我爬动态爬了10多t流量 好像就是那天早上加了-352 在此之前是没有的
我用了代理池就没这个问题
库问题应该是4xx 你可以用go试下 如果还是-352那应该就是ip问题 开tun模式试下

**Comment by djkcyl** [comment]
我试了下，删掉了所有的metadata，只留了ua和device bin，出了个新的报错：

```
(bilireq-3.10) root@as:~/bilireq# python test/test_grpc.py 
{'user-agent': 'Dalvik/2.1.0 (Linux; Android) os/android',
 'x-bili-device-bin': b''}

Traceback (most recent call last):
  File "/root/bilireq/test/test_grpc.py", line 92, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/bilireq/test/test_grpc.py", line 74, in main
    dynamics = await grpc_get_user_dynamics(uid=491589125)
  File "/root/bilireq/bilireq/grpc/utils/__init__.py", line 48, in wrapper
    result = await func(
  File "/root/bilireq/bilireq/grpc/dynamic/__init__.py", line 26, in grpc_get_user_dynamics
    return await stub.DynSpace(req, **kwargs)
  File "/root/bilireq/.venv/lib/python3.10/site-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "grpc: Decompressor is not installed for grpc-encoding "deflate""
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"grpc: Decompressor is not installed for grpc-encoding \"deflate\"", grpc_status:12, created_time:"2023-08-30T09:06:53.605232597+08:00"}"
>
```

这个报错在半个月之前是加了个 buvid 就解决了，然后现在加 buvid 也不管用了，貌似我只要给 device-bin 里填充了内容就会 -352

**Comment by djkcyl** [comment]
用 httpx 手搓的grpc请求是正常的，换了库就出问题了

```python
msg = DynSpaceReq()
msg.host_uid = 491589125
# msg.local_time = 8
# msg.page = 1
proto = msg.SerializeToString()
print(proto)

data = b"\0" + len(proto).to_bytes(4, "big") + proto

headers = {
    "User-Agent": "Dalvik/2.1.0 (Linux; Android) os/android",
    "Content-Type": "application/grpc",
    "x-bili-device-bin": "",
}

resp = httpx.post("https://app.bilibili.com/bilibili.app.dynamic.v2.Dynamic/DynSpace", data=data, headers=headers)
resp.raise_for_status()

gresp = DynSpaceRsp()
gresp.ParseFromString(resp.content[5:])

print(gresp)
```

![image](https://github.com/SocialSisterYi/bilibili-API-collect/assets/59153990/711b9aab-d276-481d-8295-debd38159805)

**Comment by cxw620** [comment]
那有可能是这个库存在什么特征, 给针对性 ban 掉了. 不过我用 Rust 的 tonic 是没问题的, 可能因为 tonic 并不是 gRPC 的官方实现?

**Comment by cxw620** [comment]
> 这是开了 grpc.Compression.NoCompression 和 grpc.Compression.Gzip 的
> 
> ```
> grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
>         status = StatusCode.UNKNOWN
>         details = "Stream removed"
>         debug_error_string = "UNKNOWN:Error received from peer ipv4:114.230.222.142:443 {created_time:"2023-08-30T09:32:16.5829016+08:00", grpc_status:2, grpc_message:"Stream removed"}"
> >
> ```
> 
> 这个报错在半个月之前是加了个 buvid 就解决了，然后现在加 buvid 也不管用了，貌似我只要给 device-bin 里填充了内容就会 -352

Stream removed 似乎不是风控的, 换 grpc.biliapi.net 这个原生 gRPC 接口看看?

**Comment by cxw620** [comment]
刚刚我也使用 Rust tonic 测试了一下, 亦无法复现这问题, 合理怀疑产生这问题的原因: 
- gRPC 库存在特征, 被针对性风控
- IP 或者 access_key 黑了

所以尝试更换 IP, 最好换运营商, 例如用手机流量, 换 gRPC 库换 access_key 或者不要 access_key 再试试. 

测试样例(仅供参考, 里面有大量我自己封装的 func): 
```rust
    #[tokio::test]
    async fn test_v2_dynamic() -> Result<(), String> {
        let client_arc = GRPC_HTTPS_CLIENT_TEST.clone();
        let hyper_https_client = client_arc.get("a1playurl").unwrap().clone();
        let user_info = ClientUserInfo {
            uid: ***,
            access_key: "***".to_owned(),
            ..Default::default()
        };
        let client_info = ClientInfo {
            user_info,
            app_info: ClientAppInfo::default(),
            device_info: ClientDeviceInfo::default(),
        };
        let bili_header = BiliGrpcHeaders::new(&client_info);
        let bili_upstream_uri = hyper::Uri::from_static("https://app.bilibili.com");

        let req = bapis::app::dynamic::v2::DynSpaceReq {
            host_uid: 491589125,
            local_time: 8,
            page: 1,
            ..Default::default()
        };

        let resp = moss_handler!(
            bili_header,
            bili_upstream_uri,
            hyper_https_client,
            bapis::app::dynamic::v2::dynamic_client::DynamicClient
        )
        .dyn_space(req)
        .await;
        match resp {
            Ok(resp) => {
                use tokio::fs;
                let resp_str = format!("{:#?}", resp.get_ref());
                fs::write("cn_space.txt", resp_str).await.unwrap();
                // println!("{:?}", resp);
                Ok(())
            }
            Err(e) => {
                println!("{:?}", e);
                let bili_error = BiliError::from(e);
                Err(format!("{}", bili_error))
            }
        }
    }
```

**Comment by Well2333** [comment]
我认为IP不是问题的关键，此问题的广泛出现理论上和IP并不相关，而且其中包括了大量非数据中心的常规民用线路的IP。

参考上述讨论，很有可能是python的grpc库出现问题了，可以以此为方向尝试解决？

**Comment by cxw620** [comment]
鉴于 Python 是 gRPC 官方支持的语言之一, 我搜了搜没找到合适的第三方库, 我觉得像前面 My-Responsitories那样简单手搓个 gRPC Client 就好, 需要什么功能再加就是()

**Comment by Well2333** [comment]
> 鉴于 Python 是 gRPC 官方支持的语言之一, 我搜了搜没找到合适的第三方库, 我觉得像前面 My-Responsitories那样简单手搓个 gRPC Client 就好, 需要什么功能再加就是()

要说没有的话，确实也有一些，比如 [grpclib](https://grpclib.readthedocs.io/en/latest/) 或者 aiogrpc(三年没更新了)，不过迁移成本有点高，也不确定是不是 grpcio 造成的问题还是 python 的问题，总之仍需要进一步测试

**Comment by cctyl** [comment]
我也同样出现-352问题，这是我的metdata配置：[https://github.com/cctyl/BiliRecommBehaviorCorrection/blob/main/src/main/java/io/github/cctyl/interceptor/GrpcInterceptor.java](url)
这是我的请求代码：
`    @Test
    void test() {
        DynamicRpcProto.DynDetailReply dynDetailReply = dynamicBlockingStub.dynDetail(DynamicRpcProto.DynDetailReq.newBuilder()
                .setDynamicId("824093109029699590")
                .build());
        log.info(dynDetailReply.toString());
    }`

直接出现了UNKNOWN: -352的问题

**Comment by cxw620** [comment]
> 直接出现了UNKNOWN: -352的问题

你康康你代码里 build 写 `7110300`, version 却写了 `7.38.0`, 还有一次性的 sessionId 给写死了, UA 里面的设备 model 也和你 metadata 里面的对不上, 被风控也不奇怪.

**Comment by cctyl** [comment]
> > 直接出现了UNKNOWN: -352的问题
> 
> 你康康你代码里 build 写 `7110300`, version 却写了 `7.38.0`, 还有一次性的 sessionId 给写死了, UA 里面的设备 model 也和你 metadata 里面的对不上, 被风控也不奇怪.

哈哈好的。我改一下，谢谢指点。其实我发现是我的access_key格式错了，改了就正常了。我在想它们的服务器是否真的会校验多个字段的一致性，可能发送多次会导致风控，我这还是首次发起

**Comment by cctyl** [comment]
> > 直接出现了UNKNOWN: -352的问题
> 
> 你康康你代码里 build 写 `7110300`, version 却写了 `7.38.0`, 还有一次性的 sessionId 给写死了, UA 里面的设备 model 也和你 metadata 里面的对不上, 被风控也不奇怪.

这个sessionId 生成的规则是什么呢？proto的注释是 0-9 a-z，任意混合成32位即可吗

**Comment by cxw620** [comment]
> 这个sessionId 生成的规则是什么呢？proto的注释是 0-9 a-z，任意混合成32位即可吗

不清楚, 没深究, 应该随机问题不大, 我就那么操作的. 还有更正一下是 8 位, 0-9, a-f.

**Comment by FishZe** [comment]
> 用 httpx 手搓的grpc请求是正常的，换了库就出问题了
> 
> ```python
> msg = DynSpaceReq()
> msg.host_uid = 491589125
> # msg.local_time = 8
> # msg.page = 1
> proto = msg.SerializeToString()
> print(proto)
> 
> data = b"\0" + len(proto).to_bytes(4, "big") + proto
> 
> headers = {
>     "User-Agent": "Dalvik/2.1.0 (Linux; Android) os/android",
>     "Content-Type": "application/grpc",
>     "x-bili-device-bin": "",
> }
> 
> resp = httpx.post("https://app.bilibili.com/bilibili.app.dynamic.v2.Dynamic/DynSpace", data=data, headers=headers)
> resp.raise_for_status()
> 
> gresp = DynSpaceRsp()
> gresp.ParseFromString(resp.content[5:])
> 
> print(gresp)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/59153990/264200419-711b9aab-d276-481d-8295-debd38159805.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1ODE1NTYsIm5iZiI6MTcwMjU4MTI1NiwicGF0aCI6Ii81OTE1Mzk5MC8yNjQyMDA0MTktNzExYjlhYWItZDI3Ni00ODFkLTgyOTUtZGViZDM4MTU5ODA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE5MTQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlY2U1MjFiMDFhNTk4NzZkMzhkYzk0MjJmMzIyOGRkZWFiNjU5MTk4Mzk5ZDQ1Mjg5Y2VjNDU0M2FhNDZlYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RjAvgIMgORG1-NwNRY0oTbpvDF0ozp-qdt1b8o-Qi9I)

尝试使用了这段代码进行请求，`resp.content`内容为空。在运行代码的服务器上搭建代理，手机连接代理服务器b站请求正常，似乎和IP无关，应该还有其他风控内容。
